version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: admin

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"     # REST API
      - "6334:6334"     # gRPC (opzionale)
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  app:
    build: back
    environment:
      MONGO_URI: mongodb://admin:password@mongodb:27017/
      QDRANT_HOST: http://qdrant:6333
    depends_on:
      - mongodb
      - qdrant

volumes:
  qdrant_data:
